---
title: Chen
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: |
  Stay hungry, stay curious.
baseurl: "/"
url: http://yourdomain.com
gems:
- jekyll-paginate
paginate: 5
markdown: kramdown
